# Deployment config that will run whenever we make a pull and merge request in auth. 

name: deploy-auth

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch and auth directory
   push:
    branches: 
      - master
    paths:
      - 'auth/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create kubeconfig 
        run: |
          mkdir ${HOME}/.kube
          echo secrets.KUBE_CONFIG | base64 --decode > ${HOME}/.kube/config
          cat ${HOME}/.kube/config
        env: 
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      - name: Use context
        run: kubectl config use-context vke-f1f12d79-0e76-413a-90f5-aa48df4e6136
      
      
