name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - "infra/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo $KUBE_CONFIG | base64 -di > ${HOME}/.kube/config
          cat ${HOME}/.kube/config
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      - name: Use context
        run: kubectl config use-context vke-d79bf1a3-bb11-429a-a9c4-14e030731996
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
