# Deployment config that will run whenever we make a pull and merge request in auth. 

name: deploy-auth

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch and auth directory
   push:
    branches: 
      - master
    paths:
      - 'auth/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: mkdir ${HOME}/.kube
      - name: kubeconfig
        run: |
          echo $KUBE_CONFIG > ${HOME}/.kube/config-encoded 
          cat ${HOME}/.kube/config-encoded | base64 --decode 
        env: 
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
     
      - name: Use context
        run: kubectl config use-context vke-f1f12d79-0e76-413a-90f5-aa48df4e6136
      # we want to build a new image and push it to docker hub. 
      - run: cd auth && docker build -t idrahmed/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push idrahmed/auth
      
      
